n = int(input ("Ingresa el semestre en el que estas:"))

if semestre == 1:
   print("CALCULO DIFERENCIAL")
   print("FUNDAMENTOS DE PROGRAMACIÓN")
   print("MATEMATICAS DISCRETAS")
   print("INTRODUCCIÓN A LAS TIC´S")
   print("TALLER DE ÉTICA")
   print("FUNDAMENTOS DE INVESTIGACIÓN")
if semestre == 2:
   print("CALCULO INTEGRAL")
   print("PROGRAMACIÓN ORIENTADA A OBJETOS")
   print("MATEMATICAS DISCRETAS II")
   print("PROBABILIDAD Y ESTADISTICA")
   print("CONTABILIDAD Y COSTOS")
   print("MATEMÁTICAS APLICADAS A COMUNICACIONES")
if semestre == 3:
   print("ESTRUCTURA Y ORGANIZACIÓN DE DATOS")
   print("ADMINISTRACIÓN GERENCIAL")
   print("FUNDAMENTOS DE BASE DE DATOS")
   print("ELECTRICIDAD Y MAGNETISMO")
   print("ALGEBRA LINEAL")
   print("ANÁLISIS DE SEÑALES Y SISTEMAS DE COMUNICACIÓN")
if semestre == 4:
   print("PROGRAMACIÓN II")
   print("MATEMÁTICAS PARA LA TOMA DE DECISIONES")
   print("TALLER DE BASE DE DATOS")
   print("CIRCUITOS ELÉCTRICOS Y ELECTRÓNICOS")
   print("INGENIERÍA DE SOFTWARE")
   print("FUNDAMENTOS DE REDES")
if semestre == 5:
   print("TELECOMUNICACIONES")
   print("ADMINISTRACIÓN DE PROYECTOS")
   print("BASE DE DATOS DISTRIBUIDAS")
   print("ARQUITECTURA DE COMPUTADORAS")
   print("TALLER DE INGENIERIA EN SOFTWARE")
   print("REDES DE COMPUTADORAS")
if semestre == 6:
   print("PROGRAMACIÓN WEB")
   print("DESARROLLO DE EMPRENDEDORES")
   print("TALLER DE INVESTIGACIÓN")
   print("SISTEMA OPERATIVOS I")
   print("TECNOLOGÍAS INALÁMBRICAS")
   print("REDES EMERGENTES")
if semestre == 7:
   print("DESARROLLO DE APLICACIONES PARA DISPOSITIVOS MOVILES")
   print("DESARROLLO SUSTENTABLE")
   print("TALLER DE INVESTIGACIÓN II")
   print("SISTEMA OPERATIVOS II")
   print("NEGOCIOS ELECTRONICOS I")
   print("ADMINISTRACIÓN Y SEGURIDAD DE REDES")
if semestre == 8:
   print("AUDITORÍA EN TECNOLOGÍAS DE LA INFORMACIÓN")
   print("INTERACCIÓN HUMANO COMPUTADORA")
   print("INGENIERÍA DEL CONOCIMIENTO")
   print("NEGOCIOS ELECTRONICOS II")
   
else:
   print("No existe")
